/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemon;

import javax.swing.DefaultListModel;

/**
 *
 * @author JOAOPEDROBACKXAVIER
 */
public class pokemonStorage extends javax.swing.JFrame {

    /**
     * Creates new form pokemonStorage
     */
    Pokemon pikachu = new Pokemon("pikachu","eletrico", 25);
    Pokemon charmander = new Pokemon("charmander","flame", 5);
    Pokemon charmelion = new Pokemon("charmelion","flame", 19);
    Pokemon charizard = new Pokemon("charizard","flame", 40);
    Pokemon servine = new Pokemon("servine","grass", 7);
    Pokemon vaporion = new Pokemon("vaporion","water", 30);
    Pokemon nidorino = new Pokemon("nidorino","eletrico", 6);
    Pokemon bulbasaur = new Pokemon("bulbasaur","grass", 9);
    Pokemon ivysaur = new Pokemon("ivysaur","grass", 22);
    Pokemon venusaur = new Pokemon("venusaur","grass", 35);
    Pokemon squirtle = new Pokemon("squirtle","water", 6);
    Pokemon wartortle = new Pokemon("wartortle","water", 19);
    Pokemon blastoise = new Pokemon("blastoise","water", 50);
    Pokemon caterpie = new Pokemon("caterpie","insect", 3);
    public pokemonStorage() {
        initComponents();
        modelo1.addElement(pikachu.getInfo());
        modelo1.addElement(charmander.getInfo());
        modelo1.addElement(charmelion.getInfo());
        modelo1.addElement(charizard.getInfo());
        modelo1.addElement(servine.getInfo());
        modelo1.addElement(vaporion.getInfo());
        modelo1.addElement(nidorino.getInfo());
        modelo1.addElement(bulbasaur.getInfo());
        modelo1.addElement(venusaur.getInfo());
        modelo1.addElement(squirtle.getInfo());
        modelo1.addElement(wartortle.getInfo());
        modelo1.addElement(blastoise.getInfo());
        modelo1.addElement(caterpie.getInfo());
        modelo1.addElement(ivysaur.getInfo());
        computerlist.setModel(modelo1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerlist = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        backpackList = new javax.swing.JList<>();
        backpackAdd = new javax.swing.JButton();
        computerAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Computer");

        label2.setText("Backpack");

        jScrollPane1.setViewportView(computerlist);

        jScrollPane2.setViewportView(backpackList);

        backpackAdd.setText("add to backpack");
        backpackAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backpackAddMouseClicked(evt);
            }
        });

        computerAdd.setText("add to computer");
        computerAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computerAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(backpackAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(computerAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(label2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backpackAdd)
                    .addComponent(computerAdd))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    
    DefaultListModel<String> modelo1 = new DefaultListModel<>();
    DefaultListModel<String> modelo2 = new DefaultListModel<>();
    
    
    private void backpackAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpackAddMouseClicked
     int[] selectedIndices = computerlist.getSelectedIndices(); 
    if (selectedIndices.length > 0) {
        for (int i = selectedIndices.length - 1; i >= 0; i--) {
            int index = selectedIndices[i];

            
            if (modelo2.getSize() < 6) {
                modelo2.addElement(modelo1.getElementAt(index)); 
                modelo1.remove(index); 
            } else {
                break; 
            }
        }
    }
    backpackList.setModel(modelo2); 
    computerlist.setModel(modelo1); 
    }//GEN-LAST:event_backpackAddMouseClicked

    private void computerAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerAddMouseClicked
            int[] selectedIndices = backpackList.getSelectedIndices();  
    if (selectedIndices.length > 0) {
        for (int i = selectedIndices.length - 1; i >= 0; i--) {
            int index = selectedIndices[i];
            modelo1.addElement(modelo2.getElementAt(index)); 
            modelo2.remove(index);
        }
    }
    backpackList.setModel(modelo2); 
    computerlist.setModel(modelo1); 
    }//GEN-LAST:event_computerAddMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokemonStorage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backpackAdd;
    private javax.swing.JList<String> backpackList;
    private javax.swing.JButton computerAdd;
    private javax.swing.JList<String> computerlist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
